In [1]:
# import required libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import *

In [3]:
# inline plotting

In [4]:
%matplotlib inline

In [5]:
# import the dataset

In [6]:
df=pd.read_csv('./datasets/HousingData.csv')
df.head()

Purchase time passed(1990)  Pricing
0                         1.1    39343
1                         1.2    46205
2                         1.5    37731
3                         2.0    43525
4                         2.2    39891

In [7]:
# separate dependent and independent matrix

In [8]:
X=df.iloc[:,:-1].values
X

array([[ 1.1],
       [ 1.2],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.8],
       [ 3. ],
       [ 3.2],
       [ 3.3],
       [ 3.8],
       [ 3.9],
       [ 4. ],
       [ 4.1],
       [ 4.2],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.5],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.3],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [9]:
x=df.iloc[:,1].values
x

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101000, 113122,
       109211, 105311, 116611, 112422, 122432, 123322], dtype=int64)

In [10]:
# check if there is any missing values
df[(df['Purchase time passed(1990)']==np.NaN)|(df['Pricing']==np.NaN)]

Empty DataFrame
Columns: [Purchase time passed(1990), Pricing]
Index: []

In [11]:
# create training and test datasets for independent and dependent matrix

In [12]:
X_train, X_test, x_train, x_test = train_test_split(X,x,test_size=0.3)

In [13]:
X_train

array([[10.5],
       [ 5.5],
       [ 4. ],
       [ 4.5],
       [ 8.2],
       [ 1.5],
       [ 7.3],
       [ 1.2],
       [ 2.8],
       [ 8.7],
       [ 9. ],
       [ 7.9],
       [ 4.2],
       [ 4.1],
       [10.3],
       [ 5.9],
       [ 5.1],
       [ 3. ],
       [ 3.2],
       [ 6.8],
       [ 4.9]])

In [14]:
X_test

array([[2. ],
       [6. ],
       [3.9],
       [1.1],
       [2.2],
       [9.6],
       [3.3],
       [3.8],
       [9.5]])

In [15]:
x_train

array([123322,  83088,  55794,  61111, 113122,  37731,  98273,  46205,
        56642, 109211, 105311, 101000,  57081,  56957, 122432,  81363,
        66029,  60150,  54445,  91738,  67938], dtype=int64)

In [16]:
x_test

array([ 43525,  93940,  63218,  39343,  39891, 112422,  64445,  57189,
       116611], dtype=int64)

In [17]:
# Feature Scaling of just X - training and test datasets
# scale_X=StandardScaler()
# X_train=scale_X.fit_transform(X_train)
# X_train

In [18]:
# Feature Scaling is not required USUALLY in linear regression

In [19]:
from sklearn.linear_model import LinearRegression

In [20]:
regressor=LinearRegression()

In [21]:
regressor.fit(X_train,x_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
# create a predictor to predict

In [23]:
x_predictor=regressor.predict(X_test)

In [24]:
x_predictor

array([ 43958.07803708,  81860.08123402,  61961.52955563,  35430.12731777,
        45853.17819693, 115971.88411125,  56276.22907609,  61013.9794757 ,
       115024.33403133])

In [25]:
x_test

array([ 43525,  93940,  63218,  39343,  39891, 112422,  64445,  57189,
       116611], dtype=int64)

In [26]:
# plotting info for training dataset
plt.scatter(X_train,x_train)
plt.plot(X_train,regressor.predict(X_train))
plt.title("Time v/s Price - Training")

Text(0.5, 1.0, 'Time v/s Price - Training')

In [27]:
# plotting info for testing dataset
plt.scatter(X_test,x_test)
plt.plot(X_test,regressor.predict(X_test))
plt.title("Time v/s Price - Testing")

Text(0.5, 1.0, 'Time v/s Price - Testing')