In [1]:
# import required libraries

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [4]:
# inline plotting

In [5]:
%matplotlib inline

In [6]:
# import the dataset

In [7]:
df=pd.read_csv('./datasets/HousingData.csv')
df.head()

Purchase time passed(1990)  Pricing
0                         1.1    39343
1                         1.2    46205
2                         1.5    37731
3                         2.0    43525
4                         2.2    39891

In [8]:
# separate dependent and independent matrix

In [10]:
X=df.iloc[:,0].values
X

array([ 1.1,  1.2,  1.5,  2. ,  2.2,  2.8,  3. ,  3.2,  3.3,  3.8,  3.9,
        4. ,  4.1,  4.2,  4.5,  4.9,  5.1,  5.5,  5.9,  6. ,  6.8,  7.3,
        7.9,  8.2,  8.7,  9. ,  9.5,  9.6, 10.3, 10.5])

In [12]:
x=df.iloc[:,1].values
x

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101000, 113122,
       109211, 105311, 116611, 112422, 122432, 123322], dtype=int64)

In [15]:
# check if there is any missing values
df[(df['Purchase time passed(1990)']==np.NaN)|(df['Pricing']==np.NaN)]

Empty DataFrame
Columns: [Purchase time passed(1990), Pricing]
Index: []

In [17]:
# create training and test datasets for independent and dependent matrix

In [20]:
X_train, X_test, x_train, x_test = train_test_split(X,x,test_size=0.3)

In [21]:
X_train

array([ 1.5,  2.8, 10.3,  3. ,  9. , 10.5,  3.9,  5.9,  4.5,  6.8,  8.7,
        2.2,  4.1,  9.6,  4.9,  7.9,  7.3,  8.2,  3.2,  5.5,  3.8])

In [22]:
X_test

array([9.5, 5.1, 4.2, 2. , 1.2, 4. , 6. , 3.3, 1.1])

In [23]:
x_train

array([ 37731,  56642, 122432,  60150, 105311, 123322,  63218,  81363,
        61111,  91738, 109211,  39891,  56957, 112422,  67938, 101000,
        98273, 113122,  54445,  83088,  57189], dtype=int64)

In [24]:
x_test

array([116611,  66029,  57081,  43525,  46205,  55794,  93940,  64445,
        39343], dtype=int64)